DotNET2018/WebFilms/Controllers/CommentsController.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFilms.Models;

namespace WebFilms.Controllers
{
    public class CommentsController : Controller
    {
        // GET: Comments
        public ActionResult Comments(int idMovie)
        {
            wcfWeb.WCFServiceClient host = new wcfWeb.WCFServiceClient();
            host.Open();

            CommentDTO[] comments = host.getCommentsFor(idMovie);
            List<CommentModel> Comments = new List<CommentModel>();
            foreach(CommentDTO comment in comments)
            {
                Comments.Add(new CommentModel(comment.Content,comment.Rate,comment.IDFilm,comment.Avatar,comment.Date));
            }
            if (Comments.Count < 1)
                Comments.Add(new CommentModel("CHECKUP_ADMIN", 0, idMovie, "",DateTime.Today));

            return View(Comments);
        }

        public ActionResult New(int idMovie)
        {
            CommentModel comment = new CommentModel();
            comment.Idfilm = idMovie;
            return View(comment);
        }

        public ActionResult Cancel(int idFilm)
        {
            return RedirectToAction("Comments", new { idMovie = idFilm });
        }

        public ActionResult Edit(CommentModel comment)
        {
            wcfWeb.WCFServiceClient host = new wcfWeb.WCFServiceClient();
            host.Open();
            if (comment.Avatar == null )
                return RedirectToAction("New",new { idMovie = comment.Idfilm });
            CommentDTO Comment = new CommentDTO(comment.Content, Convert.ToInt32(comment.Rate),comment.Idfilm, comment.Avatar);
            if (Comment.Content == null)
                Comment.Content = "";
            host.InsertCommentOnMovieId(Comment);

            return RedirectToAction("Comments", new { idMovie = comment.Idfilm });
        }
    }
}

DotNET2018/WebFilms/Controllers/DetailMovieController.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFilms.Models;

namespace WebFilms.Controllers
{
    public class DetailMovieController : Controller
    {
        // GET: DetailMovie
        public ActionResult Detail(int id)
        {
            FullFilmModel film = getMovie(id);

            return View(film);
        }

        private FullFilmModel getMovie(int id)
        {
            try
            {
                wcfWeb.WCFServiceClient host = new wcfWeb.WCFServiceClient();
                host.Open();

                MovieFullDTO movieFullDTO = host.GetMovieFullDetailsByMovieId(id);
                double rate = host.getAverageFor(id);
                FullFilmModel movieFull = new FullFilmModel(movieFullDTO.ID, "http://image.tmdb.org/t/p/w185" + movieFullDTO.PosterPath, movieFullDTO.Title, movieFullDTO.Runtime, rate, movieFullDTO.Actors, movieFullDTO.MovieTypes);
                return movieFull;
            }
            catch (Exception e)
            {

            }

            return new FullFilmModel();
        }
    }
}

DotNET2018/WebFilms/Views/Comments/Comments.cshtml
@model IEnumerable<WebFilms.Models.CommentModel>
@{
    ViewBag.Title = "Comments";
    int idFilm = Model.First().Idfilm;
}



<h1>@ViewBag.Title</h1>

<div>
    <p>@Html.ActionLink("Ajouter un commentaire", "New", new { idMovie = @idFilm })</p>

    <h3>Commentaires :  </h3>
    <div class="customListScrollable">
        <ul id="customListeComment">
            @foreach (var item in Model)
            {
                if (item.Content.Equals("CHECKUP_ADMIN"))
                {
                    <a>No comment yet.</a>
                }
                else
                {
                    <li>
                        <div class="customComment">
                            <div>
                                <div class="customCommentDate">@Html.DisplayFor(modelItem => item.Date)</div>
                                <strong class="customCommentName">@Html.DisplayFor(ModelItem => item.Avatar) :    </strong>
                                <img class="customStars" src="@Html.DisplayFor(modelItem => item.Star1)" />
                                <img src="@Html.DisplayFor(modelItem => item.Star2)" />
                                <img src="@Html.DisplayFor(modelItem => item.Star3)" />
                                <img src="@Html.DisplayFor(modelItem => item.Star4)" />
                                <img src="@Html.DisplayFor(modelItem => item.Star5)" />
                            </div>
                            
                            <div class="customCommentContent">@Html.DisplayFor(ModelItem => item.Content)</div>
                        </div>
                    </li>
                }
            }
        </ul>
    </div>
    <br />
    <p>@Html.ActionLink("Retour", "Detail", "DetailMovie", new { id = @idFilm }, null)</p>
</div>

DotNET2018/WebFilms/Views/Comments/New.cshtml
@model WebFilms.Models.CommentModel 
@{
    ViewBag.Title = "Ajouter un commentaire";
    int idFilm = Model.Idfilm;
}

<h2 id="customCommentTitle">@ViewBag.Title</h2>
<div class="customMainLayout">
    <div id="customMainNewComment">
        @using (Html.BeginForm("Edit", "Comments"))
        {
            <div>
                <label for="Avatar"><strong>Utilisateur</strong></label>
                <br />
                @Html.TextBoxFor(m => m.Avatar, new { @class = "customControl" })
            </div>
            <div>
                <label for="Rate"><strong>Note</strong></label>
                <br />
                @Html.TextBoxFor(m => m.Rate, new { @class = "customControl" })
            </div>
            <div>
                <label for="Content"><strong>Contenu</strong></label>
                <br />
                @Html.TextAreaFor(m => m.Content, new { @class = "customControl" })
            </div>
            <div>
                @Html.HiddenFor(m => m.Idfilm, @idFilm)
                <input type="submit" value="Ajouter" />
            </div>
        }
    </div>
</div>