DotNET2018/WebFilms/Controllers/MovieController.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFilms.Models;

namespace WebFilms.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie

        public ActionResult Movies()
        {
            var listeFilms = getMovies(0);
            return View(listeFilms);
        }

        public ActionResult Precedent(int debut)
        {
            var listeFilms = getMovies(debut - 10);
            return View("Movies", listeFilms);
        }

        public ActionResult Next(int debut)
        {
            var listeFilms = getMovies(debut + 10);
            return View("Movies", listeFilms);
        }

        private List<FilmModel> getMovies(int debut)
        {
            try
            {
                wcfWeb.WCFServiceClient host = new wcfWeb.WCFServiceClient();
                host.Open();

                MovieDTO[] moviesDTO = host.getMoviesFromXToY(debut,10);
                List<FilmModel> films = new List<FilmModel>();
                double rating = 0;
                foreach(MovieDTO movie in moviesDTO)
                {
                    rating = host.getAverageFor(movie.ID);
                    films.Add(new FilmModel(debut, movie.ID, movie.Title, movie.Runtime, rating));
                    rating = 0;
                }
                if(films.Count < 1)
                {
                    films.Add(new FilmModel(debut, 0, "No film", 0, 0));
                }
                return films;
            }
            catch(Exception e)
            {

            }
            
            return new List<FilmModel>();
        }

    }
}

DotNET2018/WebFilms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Programmation .NET : movies web</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Movies web", "Movies", "Movie", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - 2019 : Programmation .NET </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>